In [3]:
from mxnet import np, npx
npx.set_np()

In [4]:
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x.shape

(12,)

In [6]:
x.size

12

In [7]:
x = x.reshape(3, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [8]:
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
np.random.normal(0, 1, size=(3, 4))

array([[ 1.1630787 ,  2.2122064 ,  0.4838046 ,  0.7740038 ],
       [ 0.29956347,  1.0434403 ,  0.15302546,  1.1839255 ],
       [-1.1688148 ,  1.8917114 ,  1.5580711 , -1.2347414 ]])

In [12]:
np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

# Calculation

In [13]:
x=np.array([1,2,2,4])
y=np.array([2,3,3,4])
x+y,x*y,x-y,x/y

(array([3., 5., 5., 8.]),
 array([ 2.,  6.,  6., 16.]),
 array([-1., -1., -1.,  0.]),
 array([0.5      , 0.6666667, 0.6666667, 1.       ]))

In [14]:
np.exp(x)

array([ 2.7182817,  7.389056 ,  7.389056 , 54.59815  ])

In [15]:
x = np.arange(12).reshape(3, 4)
y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
np.concatenate([x, y], axis=0), np.concatenate([x, y], axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
x == y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [18]:
x.sum()

array(66.)

# broadcasting mechanism

In [27]:
a = np.arange(3).reshape(1, 1,3)
b = np.arange(6).reshape(1, 2, 3)
a, b

(array([[[0., 1., 2.]]]),
 array([[[0., 1., 2.],
         [3., 4., 5.]]]))

In [28]:
a + b

array([[[0., 2., 4.],
        [3., 5., 7.]]])

# Save mem

In [22]:
before = id(y)
y = y + x
id(y) == before

False

In [23]:
z = np.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 140534666784320
id(z): 140534666784320


In [24]:
a = x.asnumpy()
b = np.array(a)
type(a), type(b)

(numpy.ndarray, mxnet.numpy.ndarray)

In [25]:
a = np.array([3.5])
a, a.item(), float(a), int(a)

(array([3.5]), 3.5, 3.5, 3)