In [1]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

# Layers without Parameters

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward (self,X):
        return X-X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

/Users/juicydoggo/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-5.5879e-09, grad_fn=<MeanBackward0>)

# Layers with Parameters

In [10]:
class MyLinear(nn.Module):
    def __init__(self,in_units, units):
        super().__init__()
        self.weight=nn.Parameter(torch.rand((in_units, units)))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self,X):
        return F.relu(torch.mm(X,self.weight.data)+self.bias.data)

In [11]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[0.3799, 0.2683, 0.2423],
        [0.0780, 0.0324, 0.5788],
        [0.3732, 0.0532, 0.3490],
        [0.2272, 0.2109, 0.0490],
        [0.7617, 0.1037, 0.0858]], requires_grad=True)

In [12]:
linear(torch.rand(2, 5))

tensor([[2.0360, 1.3531, 1.4722],
        [2.1185, 1.4840, 1.5219]])

In [13]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[104.3109],
        [ 90.1219]])